name: ci

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint
        run: |
          make fmt
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Typecheck
        run: |
          make typecheck
  archive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          make build
      - name: Archive Flight Software
        uses: actions/upload-artifact@v4
        with:
          name: proveskit-flight-software
          path: artifacts/proves/flight-software
      - name: Archive Ground Station
        uses: actions/upload-artifact@v4
        with:
          name: proveskit-ground-station
          path: artifacts/proves/ground-station
